# frozen_string_literal: true
require 'pry'
require 'set'
require 'stringio'
require 'parser/current'
require 'unparser'
require 'erb'
require 'json'
require 'date'
require 'rack'
require 'singleton'
require 'forwardable'

require_relative 'el/utils'
require_relative 'el/html_helpers'

require_relative 'el/base'
require_relative 'el/action'
require_relative 'el/javascript'
require_relative 'el/html'
require_relative 'el/view'
require_relative 'el/page'
require_relative 'el/html_page'
require_relative 'el/json_page'
require_relative 'el/application'
require_relative 'el/action_registry'